defaults:
  - common
  - agent: sac

max_steps: 1e8
robot: HumanoidPC
eval:
  interval: 200000
  metrics:
    score: sum:default

env:
  name: BiskHurdles-v1
  train_procs: 5
  eval_procs: 50
  args:
    robot: ${robot}
  wrappers:
    - flatten_obs

agent:
  trace: true
  batch_size: 512
  randexp_samples: 10000
  warmup_samples: 10000
  rpbuf_size: 2e6
  samples_per_update: 500
  num_updates: 50

video: null # not during trainng
visdom:
  offline: true

model:
  pi: pi_d2rl_256
  q: qd_d2rl_256

optim:
  pi:
    _target_: torch.optim.Adam
    lr: 3e-4
    fuse: true
  q: ${optim.pi}
