defaults:
  - common
  - agent: sacse

max_steps: 1e7
robot: Walker
action_interval: 5
auto_adapt: true

eval:
  interval: 50000
  metrics:
    score: sum:default

env:
  name: BiskHurdles-v1
  train_procs: 1
  eval_procs: 50
  args:
    robot: ${robot}
  wrappers:
    - flatten_obs
    - time

agent:
  n_models: 5
  c_switch: ${action_interval}
  trace: true

video: null # not during trainng
visdom:
  offline: true

model:
  pi: pi_bilinear_d2rl_d_256
  q:
    name: double_q
    q_name: q_bilinear_d2rl_d_256

optim:
  pi:
    _target_: torch.optim.Adam
    lr: 3e-4
    fuse: true
  q: ${optim.pi}
